import React, { useState } from 'react';
import { motion } from 'framer-motion';
import { Download, Share2, Calendar, FileText, TrendingUp, Stethoscope } from 'lucide-react';

const MyReports = () => {
  const [reports] = useState([
    {
      id: 1,
      date: '2024-01-15',
      therapies: ['Panchakarma', 'Abhyanga', 'Shirodhara'],
      prescriptions: ['Triphala 2x daily after meals', 'Ashwagandha before bed', 'Warm sesame oil massage'],
      progress: 85,
      vaidyaNotes: 'Patient showing excellent improvement in digestion and sleep patterns. Vata dosha is well balanced. Continue current treatment for 2 more weeks.',
      vaidya: 'Dr. Sharma',
      symptoms: ['Joint pain reduced', 'Better sleep quality', 'Improved digestion']
    },
    {
      id: 2,
      date: '2024-01-08',
      therapies: ['Shirodhara', 'Herbal Steam Bath', 'Nasya'],
      prescriptions: ['Brahmi tablets morning', 'Meditation 20 mins daily', 'Pranayama exercises'],
      progress: 70,
      vaidyaNotes: 'Stress levels significantly reduced. Pitta balance improving. Patient responsive to meditation practices.',
      vaidya: 'Dr. Patel',
      symptoms: ['Reduced anxiety', 'Better focus', 'Calmer mind']
    },
    {
      id: 3,
      date: '2024-01-01',
      therapies: ['Nasya', 'Yoga therapy', 'Herbal consultation'],
      prescriptions: ['Saraswatarishta 15ml twice daily', 'Pranayama exercises', 'Kapha-reducing diet'],
      progress: 55,
      vaidyaNotes: 'Initial assessment complete. Patient responsive to treatment. Kapha constitution identified.',
      vaidya: 'Dr. Sharma',
      symptoms: ['Initial consultation', 'Baseline assessment', 'Treatment plan created']
    }
  ]);

  const generateReport = (report) => {
    const printWindow = window.open('', '_blank');
    const reportHTML = `
      <!DOCTYPE html>
      <html>
      <head>
        <title>AyurMitra Medical Report</title>
        <style>
          body { font-family: Arial, sans-serif; margin: 40px; color: #333; }
          .header { text-align: center; color: #22c55e; border-bottom: 2px solid #22c55e; padding-bottom: 20px; margin-bottom: 30px; }
          .section { margin-bottom: 25px; }
          .section-title { color: #22c55e; font-size: 18px; font-weight: bold; margin-bottom: 10px; border-bottom: 1px solid #e5e7eb; padding-bottom: 5px; }
          .progress-bar { width: 100%; height: 20px; background: #e5e7eb; border-radius: 10px; margin: 10px 0; }
          .progress-fill { height: 100%; background: linear-gradient(to right, #22c55e, #16a34a); border-radius: 10px; width: ${report.progress}%; }
          ul { list-style-type: none; padding: 0; }
          li { margin: 8px 0; padding: 8px; background: #f9fafb; border-left: 3px solid #22c55e; }
          .notes { background: #f0fdf4; padding: 15px; border-radius: 8px; border: 1px solid #bbf7d0; }
          .footer { margin-top: 40px; text-align: center; color: #6b7280; font-size: 12px; border-top: 1px solid #e5e7eb; padding-top: 20px; }
          @media print { body { margin: 20px; } }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>🌿 AyurMitra Medical Report</h1>
          <p><strong>Report Date:</strong> ${new Date(report.date).toLocaleDateString()}</p>
          <p><strong>Consulting Vaidya:</strong> ${report.vaidya}</p>
        </div>
        
        <div class="section">
          <div class="section-title">📊 Treatment Progress</div>
          <p><strong>Overall Progress: ${report.progress}%</strong></p>
          <div class="progress-bar">
            <div class="progress-fill"></div>
          </div>
        </div>
        
        <div class="section">
          <div class="section-title">🧘 Completed Therapies</div>
          <ul>
            ${report.therapies.map(therapy => `<li>• ${therapy}</li>`).join('')}
          </ul>
        </div>
        
        <div class="section">
          <div class="section-title">💊 Prescriptions & Guidelines</div>
          <ul>
            ${report.prescriptions.map(prescription => `<li>• ${prescription}</li>`).join('')}
          </ul>
        </div>
        
        <div class="section">
          <div class="section-title">✅ Symptoms & Improvements</div>
          <ul>
            ${report.symptoms.map(symptom => `<li>✓ ${symptom}</li>`).join('')}
          </ul>
        </div>
        
        <div class="section">
          <div class="section-title">📝 Vaidya Notes</div>
          <div class="notes">
            <p>${report.vaidyaNotes}</p>
          </div>
        </div>
        
        <div class="footer">
          <p>Generated by AyurMitra - Ayurvedic Wellness Platform</p>
          <p>Generated on: ${new Date().toLocaleString()}</p>
        </div>
      </body>
      </html>
    `;
    
    printWindow.document.write(reportHTML);
    printWindow.document.close();
    
    printWindow.onload = () => {
      setTimeout(() => {
        printWindow.print();
        printWindow.close();
      }, 500);
    };
  };

  const shareReport = async (report) => {
    const reportContent = `AyurMitra Medical Report\n\nDate: ${new Date(report.date).toLocaleDateString()}\nVaidya: ${report.vaidya}\nProgress: ${report.progress}%\n\nView full report for detailed treatment information.`;
    
    if (navigator.share) {
      try {
        await navigator.share({
          title: 'AyurMitra Medical Report',
          text: reportContent,
          url: window.location.href
        });
      } catch (error) {
        console.log('Sharing failed, copying to clipboard');
        navigator.clipboard.writeText(reportContent);
        alert('Report summary copied to clipboard!');
      }
    } else {
      navigator.clipboard.writeText(reportContent);
      alert('Report summary copied to clipboard!');
    }
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-green-50 via-emerald-50 to-teal-50 relative overflow-hidden">
      {/* Background Elements */}
      <div className="absolute inset-0 overflow-hidden pointer-events-none">
        {[...Array(6)].map((_, i) => (
          <motion.div
            key={i}
            animate={{
              y: [0, -20, 0],
              rotate: [0, 360],
              scale: [0.8, 1.2, 0.8]
            }}
            transition={{
              duration: 20 + i * 3,
              repeat: Infinity,
              ease: "easeInOut",
              delay: i * 2
            }}
            className="absolute opacity-10"
            style={{
              width: `${60 + i * 20}px`,
              height: `${60 + i * 20}px`,
              left: `${10 + i * 15}%`,
              top: `${15 + i * 12}%`,
              background: 'linear-gradient(45deg, #22c55e, #16a34a)',
              borderRadius: i % 2 === 0 ? '50%' : '30% 70% 70% 30%'
            }}
          />
        ))}
      </div>

      <div className="relative z-10 max-w-6xl mx-auto p-6">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: -30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8 }}
          className="text-center mb-12"
        >
          <div className="inline-flex items-center justify-center w-20 h-20 bg-gradient-to-br from-green-500 to-emerald-600 rounded-3xl mb-6 shadow-xl">
            <FileText className="w-10 h-10 text-white" />
          </div>
          <h1 className="text-5xl font-black bg-gradient-to-r from-green-600 via-emerald-600 to-teal-600 bg-clip-text text-transparent mb-4">
            My Reports
          </h1>
          <p className="text-gray-600 text-xl">
            🌿 Your complete Ayurvedic treatment history and progress
          </p>
        </motion.div>

        {/* Reports List */}
        <div className="space-y-8">
          {reports.map((report, index) => (
            <motion.div
              key={report.id}
              initial={{ opacity: 0, y: 50 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: index * 0.1 }}
              className="bg-white/95 backdrop-blur-xl rounded-3xl shadow-xl border border-green-200/50 overflow-hidden hover:shadow-2xl transition-all duration-300"
            >
              {/* Report Header */}
              <div className="bg-gradient-to-r from-green-500 to-emerald-600 p-6 text-white">
                <div className="flex justify-between items-start">
                  <div>
                    <div className="flex items-center space-x-3 mb-2">
                      <Calendar className="w-6 h-6" />
                      <h2 className="text-2xl font-bold">{new Date(report.date).toLocaleDateString('en-US', {
                        weekday: 'long',
                        year: 'numeric',
                        month: 'long',
                        day: 'numeric'
                      })}</h2>
                    </div>
                    <p className="text-green-100 flex items-center">
                      <Stethoscope className="w-4 h-4 mr-2" />
                      Vaidya: {report.vaidya}
                    </p>
                  </div>
                  <div className="flex space-x-3">
                    <motion.button
                      whileHover={{ scale: 1.05 }}
                      whileTap={{ scale: 0.95 }}
                      onClick={() => generateReport(report)}
                      className="bg-white/20 hover:bg-white/30 text-white px-4 py-2 rounded-xl flex items-center space-x-2 transition-all duration-200 backdrop-blur-sm"
                    >
                      <Download className="w-4 h-4" />
                      <span>Download</span>
                    </motion.button>
                    <motion.button
                      whileHover={{ scale: 1.05 }}
                      whileTap={{ scale: 0.95 }}
                      onClick={() => shareReport(report)}
                      className="bg-white/20 hover:bg-white/30 text-white px-4 py-2 rounded-xl flex items-center space-x-2 transition-all duration-200 backdrop-blur-sm"
                    >
                      <Share2 className="w-4 h-4" />
                      <span>Share</span>
                    </motion.button>
                  </div>
                </div>
              </div>

              {/* Report Content */}
              <div className="p-8">
                <div className="grid md:grid-cols-2 gap-8 mb-8">
                  {/* Completed Therapies */}
                  <div className="bg-gradient-to-br from-green-50 to-emerald-50 rounded-2xl p-6 border border-green-200">
                    <h3 className="text-xl font-bold text-gray-800 mb-4 flex items-center">
                      <span className="w-8 h-8 bg-green-500 rounded-lg flex items-center justify-center mr-3">
                        🧘
                      </span>
                      Completed Therapies
                    </h3>
                    <ul className="space-y-3">
                      {report.therapies.map((therapy, i) => (
                        <motion.li
                          key={i}
                          initial={{ opacity: 0, x: -20 }}
                          animate={{ opacity: 1, x: 0 }}
                          transition={{ delay: i * 0.1 }}
                          className="flex items-center text-gray-700 bg-white rounded-lg p-3 shadow-sm"
                        >
                          <div className="w-2 h-2 bg-green-500 rounded-full mr-3"></div>
                          {therapy}
                        </motion.li>
                      ))}
                    </ul>
                  </div>

                  {/* Prescriptions */}
                  <div className="bg-gradient-to-br from-blue-50 to-indigo-50 rounded-2xl p-6 border border-blue-200">
                    <h3 className="text-xl font-bold text-gray-800 mb-4 flex items-center">
                      <span className="w-8 h-8 bg-blue-500 rounded-lg flex items-center justify-center mr-3">
                        💊
                      </span>
                      Prescriptions & Guidelines
                    </h3>
                    <ul className="space-y-3">
                      {report.prescriptions.map((prescription, i) => (
                        <motion.li
                          key={i}
                          initial={{ opacity: 0, x: -20 }}
                          animate={{ opacity: 1, x: 0 }}
                          transition={{ delay: i * 0.1 }}
                          className="flex items-start text-gray-700 bg-white rounded-lg p-3 shadow-sm"
                        >
                          <div className="w-2 h-2 bg-blue-500 rounded-full mr-3 mt-2"></div>
                          {prescription}
                        </motion.li>
                      ))}
                    </ul>
                  </div>
                </div>

                {/* Progress Section */}
                <div className="bg-gradient-to-r from-purple-50 to-pink-50 rounded-2xl p-6 border border-purple-200 mb-8">
                  <div className="flex items-center justify-between mb-4">
                    <h3 className="text-xl font-bold text-gray-800 flex items-center">
                      <TrendingUp className="w-6 h-6 mr-3 text-purple-600" />
                      Treatment Progress
                    </h3>
                    <span className="text-3xl font-bold text-purple-600">{report.progress}%</span>
                  </div>
                  <div className="relative">
                    <div className="w-full bg-gray-200 rounded-full h-4">
                      <motion.div
                        initial={{ width: 0 }}
                        animate={{ width: `${report.progress}%` }}
                        transition={{ duration: 1.5, ease: "easeOut" }}
                        className="bg-gradient-to-r from-purple-500 to-pink-500 h-4 rounded-full relative overflow-hidden"
                      >
                        <motion.div
                          animate={{ x: [-100, 100] }}
                          transition={{ duration: 2, repeat: Infinity, ease: "linear" }}
                          className="absolute inset-0 bg-gradient-to-r from-transparent via-white/30 to-transparent"
                        />
                      </motion.div>
                    </div>
                  </div>
                  <div className="mt-4 grid grid-cols-1 md:grid-cols-3 gap-4">
                    {report.symptoms.map((symptom, i) => (
                      <div key={i} className="bg-white rounded-lg p-3 shadow-sm">
                        <span className="text-sm text-gray-600">✓ {symptom}</span>
                      </div>
                    ))}
                  </div>
                </div>

                {/* Vaidya Notes */}
                <div className="bg-gradient-to-br from-amber-50 to-orange-50 rounded-2xl p-6 border border-amber-200">
                  <h3 className="text-xl font-bold text-gray-800 mb-4 flex items-center">
                    <span className="w-8 h-8 bg-amber-500 rounded-lg flex items-center justify-center mr-3">
                      📝
                    </span>
                    Vaidya Notes
                  </h3>
                  <div className="bg-white rounded-xl p-4 shadow-sm border border-amber-100">
                    <p className="text-gray-700 leading-relaxed">{report.vaidyaNotes}</p>
                  </div>
                </div>
              </div>
            </motion.div>
          ))}
        </div>

        {/* Security Notice */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 1 }}
          className="mt-12 bg-gradient-to-r from-green-100 to-emerald-100 rounded-2xl p-6 border border-green-200"
        >
          <div className="flex items-center justify-center space-x-3 text-green-800">
            <div className="w-8 h-8 bg-green-500 rounded-lg flex items-center justify-center">
              🔒
            </div>
            <p className="font-semibold">
              Your medical reports are securely encrypted and can be safely shared with guardians or other healthcare providers
            </p>
          </div>
        </motion.div>
      </div>
    </div>
  );
};

export default MyReports;